config/routes.rb
Rails.application.routes.draw do
  get 'users/index'

  get 'users/show'

  get 'tasks/index'
  get 'tasks/show'
  get 'tasks/new'
  get 'tasks/edit'
  get 'tasks/home'

  get 'welcomes/home'

  devise_for :users
  resources :tasks do
    resources :tasks
  end

  resources :tasks do
      member do
          post 'completed'
      end
  end

  resources :tasks
  root 'tasks#index'

end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :user
  belongs_to :taskable, polymorphic: true
  has_many :tasks, as: :taskable
  # default_scope -> {order(created_at: :desc)}

  validates :title, presence: true, :length => {maximum: 20}
  validates :note, presence: true, :length => {maximum: 50}
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :tasks

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?

    protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name, :email, :password, :password_confirmation, :remember_me) }
    devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:login, :name, :email, :password, :remember_me) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:name, :email, :password, :password_confirmation, :current_password) }
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
before_action :set_task, only: [:show, :edit, :update]
before_action :authenticate_user!, :except => [:show, :index]
  def index
    @tasks = Task.all
  end

  def show
  end

  def new
  	@task = Task.new
  end

  def edit 
  end

  def home
  end

  def create
    if params[:task_id]
      parent = Task.find(params[:task_id])
      @task = parent.tasks.build(task_params)
    else
      @task  = Task.new(task_params)
    end
    @task.user = current_user
    if @task.save
      flash[:success] = "task created!"
      redirect_to :back
    else
      render 'new'
    end
  end

  def update
    if @task.update_attributes(task_params)
      flash[:success] = "task updated"
      redirect_to request.referrer || root_url
    end 
  end


  def destroy
  	@task = Task.find(params[:id])
      @task.destroy
  	  flash[:alert] = "Task deleted."
  	redirect_to request.referrer || root_url
  end

  def completed
    @task = Task.find(params[:id])
    if @task.update_attributes(:completed => params[:completed])
     flash[:notice] = "Task completed"
   else
     flash[:notice] = "task failed"
   end
       redirect_to root_path
  end


  private

  def set_task
  	@task = Task.find(params[:id])
  end

  def task_params
  	params.require(:task).permit(:title, :note, :completion_date, :completed)
  end
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
# before_filter :configure_sign_up_params, only: [:create]
# before_filter :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.for(:sign_up) << :name
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.for(:account_update) << :attribute
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
  #   private
  # def sign_up_params
  #    params.require(:user).permit(:name,:email,:password,:password_confirmation) if params[:user].present?
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_filter :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.for(:sign_in) << :attribute
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  	@users = User.all
  end

  def show
    if params[:id].nil? && current_user
      @user = current_user
    else
      @user = User.find(params[:id])
    end
    @tasks = @user.tasks
  end
end

app/controllers/welcomes_controller.rb
class WelcomesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcomes_helper.rb
module WelcomesHelper
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
	<div class="container">
		<%= link_to "ToDo", root_path, id: "logo" %>
		<nav>
			<ul class="nav navbar-nav navbar-right">
				<li><%= link_to "Home", root_path %></li>
		    <% if user_signed_in? %>
				<li><%= link_to "users", users_index_path %></li>
				<li class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown">
	            Account <b class="caret"></b>
	          </a>
					<ul class="dropdown-menu">
						<li><%= link_to "profile", users_show_path %></li>
						<li><%= link_to "settings", edit_user_registration_path %></li>
						<li class="divider"></li>
						<li>
							<%= link_to "Log out", destroy_user_session_path, method: "delete" %>
						</li>
					</ul>
			  </li>
        <% else %>
			  <li><%= link_to "Log in", new_user_session_path %></li>
	      <% end %>
			</ul>
		</nav>
	</div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tasklist</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<%= render 'layouts/header' %>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
<%= yield %>

</body>
</html>

app/views/tasks/_form.html.erb
<%= form_for [taskable, Task.new] do |f| %>
  <div class="form-group">
  	<%= f.label :title %>
  	<%= f.text_area :title, class:"form-control", placeholder: "Title" %>
  </div>
	<div class="form-group">
		<%= f.label :note %>
		<%= f.text_area :note, class:"form-control", placeholder: "Create a Task.." %>
	</div>
	<%= f.submit class:"btn btn-primary" %>
<% end %>

app/views/tasks/_task.html.erb
<span class="user"><%= link_to taskable.user.name, taskable %></span><br/>
<table>
    <tr>	
    	<th>Child Title</th>
      <th>Checkbox</th>
    </tr>

    <tr>
      <td><%= taskable.title %></td>
      <td> <%= form_for taskable, remote: true do |f| %>
        <%= f.check_box :completed, :class => "chil-task-check" %>
      <% end %>
    </tr>
</table>
  <span class="timestamp">
    Posted <%= time_ago_in_words(taskable.created_at) %> ago.
    <% if user_signed_in? %>
    <%= link_to "delete", taskable, method: :delete,
                                     data: { confirm: "You sure?" } %>
    <% end %>
  </span>

<script>
  $.completeTask();
</script>


 
  

app/views/tasks/edit.html.erb
<h2>Update task</h2>
<%= form_for @task do |f| %>

<p><%= f.label :title %>
	<%= f.text_area :title %>
</p>

<p><%= f.label :note %>
<%= f.text_area :note %>
</p>

<p><%= f.label :completion_date %>
	<%= f.date_field :completion_date %>
</p>

<p>
	<%= f.submit "Update task", class: "btn btn-lg btn-primary" %>
</p>
<% end %>

app/views/tasks/index.html.erb
<h1>Listing Tasks</h1>
<%= link_to 'New task', new_task_path %>
<div class="container">
	<table class="table table-hover table-bordered">
	  <tr>
	  	<th>Check</th>
	    <th>Title</th>
	    <th>Note</th>
	    <th>created_at</th>
	    <th>Completion_date</th> 
	  </tr>
	 
	  <% @tasks.each do |task| %>
	    <tr>
	    	<td> <%= form_for task, remote: true do |f| %>
	    		<%= f.check_box :completed, :class => "parent-task-check" %>
	    		<% end %>
	    	</td>
	      <td><%= task.title %></td>
	      <td><%= task.note %></td>
	      <td><%= task.created_at %></td>
	      <% if task.completed == true %>
	      <td><%= task.completion_date %></td>
	      <% else %>
	      <td>Pending</td>
	      <% end %>
        <%= render partial: 'tasks/task', collection: task.tasks, as: :taskable %>
	      <td>
	      	<%= link_to 'Show', task_path(task) %>
	        <%= link_to 'Edit', edit_task_path(task) %>
	      </td>
	    </tr>
	    <% end %>
	</table>
</div>
<script>
	$.completeTask();
</script>

app/views/tasks/new.html.erb
<h2>New Task</h2>
<%= form_for @task do |f| %>

<p><%= f.label :title %>
	<%= f.text_area :title %>
</p>

<p><%= f.label :note %>
<%= f.text_area :note %>
</p>
<%= f.submit "Create a task", class: "btn btn-lg btn-primary" %>
</p>
<% end %>

app/views/tasks/show.html.erb
  <table>
	 <tr>	
	  	<th>Parent task Title</th>
	 </tr>
	 <tr>
	  <td><%= @task.title %></td>
	</tr>
</table>
<%= render partial: 'tasks/task', collection: @task.tasks, as: :taskable %>
<%= render partial: 'tasks/form', locals: {taskable: @task} %>

app/views/users/_user.html.erb
<li>
  <%= link_to user.name, user %>
  | <%= link_to "delete", user, method: :delete,
                     data: { confirm: "You sure?" } %>
</li>

app/views/users/index.html.erb
<h1>All Users</h1>

<ul class="users">
	<% @users.each do |user| %>
		<li><%= user.name  %></li>
	<% end %>
</ul>

app/views/users/show.html.erb
<div class="row">
  <aside class="col-md-4">
    <section>
      <h1>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
  <div class="col-md-8">
      <h3>tasks (<%= @tasks.count %>)</h3>
      <ol class="tasks">
        <%= render partial: 'tasks/task', collection: @tasks, as: :taskable %>
      </ol>
  </div>
</div>

app/views/welcomes/home.html.erb
<% if user_signed_in? %>
<div class="row">
	<aside class="col-md-4">
		<section class="user_info">
			<%= render 'shared/user_info' %>
    </section>
		<section class="article_form">
			<%= render 'shared/task_form' %>
		</section>
	</aside><div class="jumbotron">
	<% else %>
	<h1>Welcome to ToDo<h1>
		<%= link_to "Sign up", new_user_registration_path, class: "btn btn-lg btn-default" %>
</div>
<% end %>